#!/usr/bin/env bash
# Generate .context/SESSION_BRIEF.md — a quick snapshot for LLM coding sessions.
# Deterministic, fast, no external services.
set -euo pipefail

OUT=".context/SESSION_BRIEF.md"
mkdir -p .context

DEFAULT_BRANCH=$(git symbolic-ref refs/remotes/origin/HEAD 2>/dev/null | sed 's@^refs/remotes/origin/@@' || echo "main")

cat > "$OUT" <<HEADER
# Session Brief
<!-- Auto-generated by scripts/make_session_brief.sh — do not hand-edit -->

HEADER

# --- Recent commits ---
{
  echo "## Recent commits"
  echo '```'
  git log -n 20 --oneline 2>/dev/null || echo "(no commits)"
  echo '```'
  echo ""
} >> "$OUT"

# --- Working tree status ---
{
  echo "## Working tree status"
  echo '```'
  git status --porcelain 2>/dev/null || echo "(clean)"
  echo '```'
  echo ""
} >> "$OUT"

# --- Diffstat vs default branch ---
{
  echo "## Diffstat vs ${DEFAULT_BRANCH}"
  echo '```'
  git diff --stat "${DEFAULT_BRANCH}" 2>/dev/null || echo "(no diff or branch not found)"
  echo '```'
  echo ""
} >> "$OUT"

# --- Experiments directory ---
if [ -d "experiments" ]; then
  {
    echo "## Experiments"
    echo '```'
    ls -1 experiments/
    echo '```'
    echo ""
  } >> "$OUT"
fi

# --- ADRs ---
if [ -d "adr" ]; then
  {
    echo "## Architecture Decision Records"
    echo '```'
    ls -1t adr/ | head -10
    echo '```'
    echo ""
  } >> "$OUT"
fi

echo "Wrote $OUT"
